In [188]:
import urllib2
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from keras.layers import Dense, LSTM, Convolution1D, MaxPooling1D
from keras.models import Sequential
from keras.datasets import imdb
from keras.preprocessing import sequence
from keras.layers.embeddings import Embedding

In [164]:
import pandas as pd
df = pd.DataFrame(columns=['sentiment', 'comment'])
columns=['sentiment', 'comment']

In [166]:
page_open = 'https://www.imdb.com/title/tt5956100/reviews'
page = urllib2.urlopen(page_open)

In [167]:
soup = BeautifulSoup(page)

In [168]:
name_box = soup.find('div', attrs={'class': 'lister-list'})
count=0

In [169]:
    #def scrap(name_box):
    for i in name_box.find_all('div',attrs={'class':'lister-item mode-detail imdb-user-review  collapsable'}):
        
        z= i.find('div',attrs={'class':'text show-more__control'})
        review = z.text.strip()
        q= i.find('span',attrs={'class':'rating-other-user-rating'})
        senti=q.find('span')
        senti = senti.text.strip()
        df.loc[count] = [senti, review]
        #df.append('sentiment'=senti,'comment'=review,'helpfull'=helpfull_comment)
        count=count+1
    #scrap(name_box)

In [172]:
df

sentiment                                            comment
66          0  The director did a fantastic job so did Salman...
67         10  Everyone should must watch this movie. Truly f...
68          1  Extremely boring and pathetic film by salmon k...
69          1  Only good thing about this movie was atif asla...
70          1  Total brainless movie. So I will alao write a ...
71         10  Movie: Tiger Zinda Hai (UA): Action - HindiPos...
72         10  Edge of the seat action thriller. fast paced s...
73         10  ITS A HUGE COMPLEMENT OF SALMAN FAN'S..!!!!!!!...
74         10  Best Movie of the Decade.. There may be lot of...
75         10  TigerZindaHai in one word - BRILLIANT!A sequel...
0           7  The whole idea of watching a movie is to get e...
1           5  Today, one is so much familiar with the type o...
2           2  I watched this movie on Christmas eve with pac...
3           1  Background music to some extent is good.\nSalm...
4           6  Salman Khan never dissappoints at the box offi...
5           1  As expected,one more salman khan movie with no...
6           1  Again and Again Bhai proves how un-evlolved he...
7           4  Movie was good for first 10 minutes and after ...
8           4  No logic in fight scenes. Story is weak, have ...
9           1  Appeasement and glorification of real life cri...
10          1  I am telling you again, save your time, and mo...
11          4  Not much as expected, but what was expected th...
12          3  So when you go to watch Salman khan movie you ...
13          6  This movie has no connection with the incident...
14          4  While the film is largely testosterone-laced, ...
15          5  I Expected a lot...There is no Creativity in s...
16          6  I rated this movie 6/10. It could easily have ...
17          5  3 *** movie! \nWhere did it lose it stars?!\nI...
18          1  If you llate salman khan fan this movie may wo...
19          2  2 stars just for action. I liked the wolf-chas...
..        ...                                                ...
88         10  I think this is Salman best movie till to date...
89          9  If "Ek Tha Tiger" was about India-Pakistan spy...
90         10  Great movie, totally loved it.. Those who are ...
91         10  TigerZindaHai in one word - BRILLIANT!A sequel...
92          3  It is not bad film but it is not good too, Sal...
93          6  The only superstar remaining in hindi film ind...
94          4  Film doesn't meet expectations of audience ,ho...
95         10  I loved Ek Tha Tiger when it had released but ...
96          1  I shouldn't have seen this pile of garbage kno...
97          7  Tiger Zinda Hai is a film co-written and direc...
98          2  Storyline is not Properly executed. Badly cine...
99          5  Starting with Ek Tha Tiger which was a blockbu...
100         0  Really found it funny reading a few reviews .....
101        10  Such a great movie by the great actor salman k...
102         8  This movie is full with action and thriller. I...
103         8  Very nice action and thriller movie by the end...
104         8  Tiger Zinda Hai (TZH). Yes, he's alive and kic...
105        10  First of all i'm not from india and therefore ...
106         6  The whole idea of making this film was to get ...
107        10  Excellent movie. truly love it. Best movie of ...
108         8  When Indian nurses are held hostage by a relig...
109        10  Those Poor Saook Fans Who Give 1 Star To Tiger...
110        10  I watched it twice and I still loved it the se...
111         9  Yes, it is a good enjoyable movie. Yes, its a ...
112         9  Hats off to YRF and Ali Abaas Zafar for making...
113         1  Salman Khan is known to make idiotic foolish m...
114         0  If you're bored at home on a weekend and don't...
115         4  The writer and director of this movie is the s...
116         4  If you know what you're getting into, Tiger Zi...
117         1  The one star I gave is f

In [171]:
    while len(soup.find('div',attrs={'class':'load-more-data'}))>0:
        if len(soup.find('div',attrs={'class':'load-more-data'}))>0:
                load_more=soup.find('div',attrs={'class':'load-more-data'})
                load_more=load_more.get('data-key')
                print load_more
                page_open = 'https://www.imdb.com/title/tt5956100/reviews/_ajax?paginationKey='+str(load_more)
                page = urllib2.urlopen(page_open)
                soup = BeautifulSoup(page)
                name_box = soup.find('div', attrs={'class': 'lister-list'})
                for i in name_box.find_all('div',attrs={'class':'lister-item mode-detail imdb-user-review  collapsable'}):
        
                    z= i.find('div',attrs={'class':'text show-more__control'})
                    review = z.text.strip()
                    if i.find('span',attrs={'class':'rating-other-user-rating'})>0:
                        q= i.find('span',attrs={'class':'rating-other-user-rating'})
                        senti=q.find('span')
                        senti = senti.text.strip()
                    else:
                        senti=0
                    df.loc[count] = [senti, review]
                    #df.append('sentiment'=senti,'comment'=review,'helpfull'=helpfull_comment)
                    count=count+1

hzei33sfojrsx2z7mak6re5h64uxjwokteck4utneeclwjdyx6gz3mad7rprxacuypl2uc5vdbbyk
chrutbcvzzhv4ct4ucpt4v6qxy67cgrbwtfzgvac5pwktla4ft424hnxgemaz6jynlymtmsbiyhlm
gq2h37jfvleircl5sd6aqdtogazx23c7lxkon4hraomj7ym5jwxgyje6t7e7ea7w5epo7krxw4wny
ulrw2nrarmtd3epogzjt23lszjhx2cxbmcgtb3uwtkpsbuq2sqswxkm64ahblg7xct2e65ay242kq
z43wqztrlisgyee7gr6bjtuhqfg2igno3rfuwodeuftxcucegiex3dkbogj2vhgs6ql4f2fgthzcw


TypeError: object of type 'NoneType' has no len()

In [484]:
df

sentiment                                            comment  \
66          0  The director did a fantastic job so did Salman...   
67         10  Everyone should must watch this movie. Truly f...   
68          1  Extremely boring and pathetic film by salmon k...   
69          1  Only good thing about this movie was atif asla...   
70          1  Total brainless movie. So I will alao write a ...   
71         10  Movie: Tiger Zinda Hai (UA): Action - HindiPos...   
72         10  Edge of the seat action thriller. fast paced s...   
73         10  ITS A HUGE COMPLEMENT OF SALMAN FAN'S..!!!!!!!...   
74         10  Best Movie of the Decade.. There may be lot of...   
75         10  TigerZindaHai in one word - BRILLIANT!A sequel...   
0           7  The whole idea of watching a movie is to get e...   
1           5  Today, one is so much familiar with the type o...   
2           2  I watched this movie on Christmas eve with pac...   
3           1  Background music to some extent is good.\nSalm...   
4           6  Salman Khan never dissappoints at the box offi...   
5           1  As expected,one more salman khan movie with no...   
6           1  Again and Again Bhai proves how un-evlolved he...   
7           4  Movie was good for first 10 minutes and after ...   
8           4  No logic in fight scenes. Story is weak, have ...   
9           1  Appeasement and glorification of real life cri...   
10          1  I am telling you again, save your time, and mo...   
11          4  Not much as expected, but what was expected th...   
12          3  So when you go to watch Salman khan movie you ...   
13          6  This movie has no connection with the incident...   
14          4  While the film is largely testosterone-laced, ...   
15          5  I Expected a lot...There is no Creativity in s...   
16          6  I rated this movie 6/10. It could easily have ...   
17          5  3 *** movie! \nWhere did it lose it stars?!\nI...   
18          1  If you llate salman khan fan this movie may wo...   
19          2  2 stars just for action. I liked the wolf-chas...   
..        ...                                                ...   
88         10  I think this is Salman best movie till to date...   
89          9  If "Ek Tha Tiger" was about India-Pakistan spy...   
90         10  Great movie, totally loved it.. Those who are ...   
91         10  TigerZindaHai in one word - BRILLIANT!A sequel...   
92          3  It is not bad film but it is not good too, Sal...   
93          6  The only superstar remaining in hindi film ind...   
94          4  Film doesn't meet expectations of audience ,ho...   
95         10  I loved Ek Tha Tiger when it had released but ...   
96          1  I shouldn't have seen this pile of garbage kno...   
97          7  Tiger Zinda Hai is a film co-written and direc...   
98          2  Storyline is not Properly executed. Badly cine...   
99          5  Starting with Ek Tha Tiger which was a blockbu...   
100         0  Really found it funny reading a few reviews .....   
101        10  Such a great movie by the great actor salman k...   
102         8  This movie is full with action and thriller. I...   
103         8  Very nice action and thriller movie by the end...   
104         8  Tiger Zinda Hai (TZH). Yes, he's alive and kic...   
105        10  First of all i'm not from india and therefore ...   
106         6  The whole idea of making this film was to get ...   
107        10  Excellent movie. truly love it. Best movie of ...   
108         8  When Indian nurses are held hostage by a relig...   
109        10  Those Poor Saook Fans Who Give 1 Star To Tiger...   
110        10  I watched it twice and I still loved it the se...   
111         9  Yes, it is a good enjoyable movie. Yes, its a ...   
112         9  Hats off to YRF and Ali Abaas Zafar for making...   
113         1  Salman Khan is known to make idiotic foolish m...   
114         0  If you're bored at home on a weekend and don'

In [272]:
#dataset is df
import numpy as np
from string import punctuation
from os import listdir
import string
from collections import Counter
from nltk.corpus import stopwords
import numpy as np
from nltk.corpus import stopwords
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from bs4 import BeautifulSoup 
#to remove HTML delimeters
import re
#To remove punctuation and numbers, we will use a package for dealing with regular expressions, called re
import nltk

In [333]:
def clean_doc(doc):
 # split into tokens by white space
 tokens = doc.split()
 table = string.maketrans('', '')
 tokens = [w.translate(table) for w in tokens]
 # remove remaining tokens that are not alphabetic
 tokens = [word for word in tokens if word.isalpha()]
 # filter out stop words
 stop_words = set(stopwords.words('english'))
 tokens = [w for w in tokens if not w in stop_words]
 # filter out short tokens
 tokens = [word for word in tokens if len(word) > 1]
 return tokens

In [273]:
def review_to_words( raw_review ):
    review_text = BeautifulSoup(raw_review).get_text() 
    letters_only = re.sub("[^a-zA-Z]", " ", review_text) 
    words = letters_only.lower().split()                             
    #
    stops = set(stopwords.words("english"))                  
    # 
    meaningful_words = [w for w in words if not w in stops]   
    #
    return( " ".join( meaningful_words ))

In [462]:
from keras.preprocessing.text import Tokenizer
raw_text = np.hstack([df.comment.str.lower()])
raw_text=clean_doc(str(raw_text))
raw_text
clean_review = review_to_words( df['comment'][1] )
num_reviews = df["comment"].size

clean_train_reviews = []

for i in xrange( 0, num_reviews ):
    clean_train_reviews.append( review_to_words( df["comment"][i] ) )
print "Cleaning and parsing the training set movie reviews...\n"
clean_train_reviews = []
for i in xrange( 0, num_reviews ):
    if( (i+1)%1000 == 0 ):
        print "Review %d of %d\n" % ( i+1, num_reviews )                                                                    
    clean_train_reviews.append( review_to_words( df["comment"][i] ))
    
    
    
print "Creating the bag of words...\n"
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000) 
train_data_features = vectorizer.fit_transform(clean_train_reviews)

train_data_features = train_data_features.toarray()
print train_data_features

Cleaning and parsing the training set movie reviews...

Creating the bag of words...

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 4 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [463]:
vocab = vectorizer.get_feature_names()

In [464]:
train_data_features

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 4, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [465]:
clean_train_reviews

[u'whole idea watching movie get entertained forgetting one daily grind getting immersed fairy tale created using light sound blissfully munching tub popcorn sure changed us wanting see realistic films travails bar dancer coping erectile dysfunction making toilets biographies sportsmen dramatically overdoing realism hey know enough goes around walk dark cinema hall wait expectantly film start getting disgusted looking realistic shorts made cigarettes chewing tobacco transported dream world created salman khan make one else sequence sequence get convinced invincibility stupidity well ends well watch lovers either getting killed committing suicide end casting director would really worked hard find spineless villain would seem like puppy front tiger shoot hero least dozen chances production values cinematography background score superb like movie embezzled today technology three actors deserve mention salman salman salman anyone else moview yes salman taken single handedly responsibility 

In [466]:

dist = np.sum(train_data_features, axis=0)

for tag, count in zip(vocab, dist):
    print count, tag

2 aa
1 aamir
1 ab
1 abaas
27 abbas
2 abducted
3 able
1 abs
1 absconded
2 absence
3 absolutely
7 abu
1 accept
2 acceptance
1 accomplish
1 accomplished
4 according
1 accordingly
1 aces
1 acried
1 acrobatics
1 across
5 act
2 acted
31 acting
125 action
4 actions
1 active
12 actor
13 actors
2 actress
4 acts
3 actual
4 actually
1 adapted
3 add
1 addition
1 additional
1 adds
2 aditya
1 adjusted
1 advantage
3 age
1 aged
2 ageing
2 agency
1 agenda
1 agendas
1 agenices
9 agent
4 agents
1 ago
2 agree
1 agrees
1 ahead
1 air
1 aka
2 akshay
1 alao
1 albeit
1 album
31 ali
4 alive
1 allow
4 almost
2 alone
5 along
2 alps
3 already
40 also
1 altall
3 although
4 always
1 aman
1 amateur
2 amazed
7 amazing
3 american
2 among
1 amount
1 analysis
2 anant
6 angad
1 anger
1 angle
2 angry
1 annoying
9 another
2 antagonist
1 anticipated
1 anupriya
1 anybody
2 anymore
3 anyone
4 anything
2 anyways
3 apart
1 apcing
1 appeal
2 appears
1 appeasement
1 applause
3 appreciate
1 apt
1 apun
1 arc
1 arguably
1 arises
6 ar

5 hindi
1 hindipositives
1 hindustan
4 hit
2 hitting
1 hoisting
1 hold
9 hollywood
4 home
2 homeground
1 honeslt
3 honest
1 honestly
1 honesty
1 hope
1 hoped
1 hopefully
1 horrible
2 horse
4 hospital
14 hostage
5 hostages
1 hostility
2 hot
1 hour
1 hours
1 house
1 household
8 however
1 http
10 huge
1 hughlight
2 huh
1 hull
2 human
5 humanity
4 humor
1 humorous
2 humour
1 hundreds
1 hunt
1 hunts
1 hurt
2 husband
1 hyped
2 idea
1 identify
1 idiocracy
1 idiot
1 idiotic
1 idiotically
1 idols
1 ignore
1 ikrit
1 illogical
1 image
2 imagine
1 immediate
1 immense
1 immersed
1 immortal
1 impact
3 important
2 importantly
3 impossible
1 impressed
1 impresses
4 impressive
1 impressively
1 improvised
3 inception
12 incident
1 included
2 including
1 incorrectly
1 incpetion
1 increasing
2 incredible
1 incredibly
1 ind
1 indeed
19 india
26 indian
3 indians
1 indicated
1 indo
1 indonesia
1 industries
2 industry
1 ing
3 ingredients
1 inhibition
1 injunctions
1 injuries
2 inside
2 inspirational
1 inspiri

7 usual
1 utter
1 uttering
1 vacuum
1 vaibhavi
1 valuable
4 value
1 values
1 variation
2 various
1 varun
1 vegetable
1 vendor
1 vent
1 verdict
1 version
1 vga
1 vicinity
2 viewers
2 viewing
9 villain
2 villian
1 vindictiveness
1 virtually
5 vishal
3 visible
1 vision
1 visits
1 visual
1 visuals
1 vs
1 vulgarity
1 wafer
1 wahabism
2 waistline
2 wait
1 waiting
1 walk
9 want
1 wanted
1 wanting
2 wants
6 war
8 waste
4 wasted
2 wasting
56 watch
5 watchable
6 watched
11 watching
18 way
1 ways
4 weak
1 weaker
1 weakest
1 wee
1 week
3 weekend
1 weekends
1 weight
1 weird
1 welcome
45 well
1 wellalthough
3 went
2 whatever
1 whats
2 whenever
2 whether
12 whole
1 whose
4 wife
1 wild
1 wildness
1 window
2 wing
3 wise
1 wiser
3 wish
1 within
21 without
1 wolf
1 wolve
6 wolves
1 woman
1 women
1 wonder
2 wonderful
1 wonderfully
2 wondering
2 wood
2 wooden
6 word
2 words
14 work
4 worked
6 working
16 world
2 worldwide
1 worse
7 worst
3 worth
3 worthy
26 would
1 wrapping
2 write
2 writer
1 writers
3 writ

In [467]:

model = Sequential()
embedding_vector_length = 32
model.add(Embedding(5000, embedding_vector_length, input_length=2310))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_16 (Embedding)     (None, 2310, 32)          160000    
_________________________________________________________________
lstm_16 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 101       
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________


In [468]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [318]:
model.fit(train_data_features,  df["sentiment"], nb_epoch=3, batch_size=10)

Epoch 1/3
118/118 [==============================] - 33s 280ms/step - loss: -47.0003 - acc: 0.2797
Epoch 2/3
118/118 [==============================] - 30s 255ms/step - loss: -59.0072 - acc: 0.2797
Epoch 3/3
118/118 [==============================] - 26s 221ms/step - loss: -66.9035 - acc: 0.2797


In [469]:
model2 = Sequential()
embedding_vector_length = 32
model2.add(Embedding(5000, embedding_vector_length, input_length=2310))
model2.add(Convolution1D(nb_filter=32, filter_length=3,activation='relu'))
model2.add(MaxPooling1D(pool_length=2))
model2.add(LSTM(100))
model2.add(Dense(1, activation='sigmoid'))
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_17 (Embedding)     (None, 2310, 32)          160000    
_________________________________________________________________
conv1d_8 (Conv1D)            (None, 2308, 32)          3104      
_________________________________________________________________
max_pooling1d_8 (MaxPooling1 (None, 1154, 32)          0         
_________________________________________________________________
lstm_17 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 101       
Total params: 216,405
Trainable params: 216,405
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", kernel_size=3, filters=32)`
  after removing the cwd from sys.path.
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=2)`
  """


In [395]:
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [392]:
model2.fit(train_data_features,  df["sentiment"], nb_epoch=3, batch_size=10)

Epoch 1/3
118/118 [==============================] - 17s 145ms/step - loss: -0.8473 - acc: 0.2542
Epoch 2/3
118/118 [==============================] - 13s 110ms/step - loss: -23.6056 - acc: 0.2797
Epoch 3/3
118/118 [==============================] - 14s 117ms/step - loss: -44.7845 - acc: 0.2797


In [480]:
a='The movie was good ,i just love the movie'

clean_train_reviews.append(review_to_words(a))

q = vectorizer.fit_transform(clean_train_reviews)

q = q.toarray()
print len(q)


121


In [482]:
w=q[120]
print w

[0 0 0 ... 0 0 0]


In [483]:
w=[w]
print w
prediction=forest.predict(w)
print prediction

[array([0, 0, 0, ..., 0, 0, 0])]
['10']


In [424]:
forest = RandomForestClassifier(n_estimators = 100) 

# Fit the forest to the training set, using the bag of words as 
# features and the sentiment labels as the response variable
#
# This may take a few minutes to run
forest = forest.fit( train_data_features, arr )


In [409]:
a=df['sentiment'].values
print a

[0 u'10' u'1' u'1' u'1' u'10' u'10' u'10' u'10' u'10' u'7' u'5' u'2' u'1'
 u'6' u'1' u'1' u'4' u'4' u'1' u'1' u'4' u'3' u'6' u'4' u'5' u'6' u'5'
 u'1' u'2' u'1' u'1' u'1' u'1' u'3' u'3' u'7' u'2' u'1' u'7' u'5' u'5'
 u'1' u'1' u'7' u'1' u'1' u'1' u'1' u'5' u'5' u'10' u'1' u'8' u'1' u'1'
 u'8' u'1' u'1' u'1' u'7' u'1' u'10' u'7' u'8' u'10' u'1' u'8' u'10' u'10'
 u'10' u'10' u'10' u'9' u'10' u'10' u'1' u'10' u'10' u'10' u'10' u'10'
 u'9' u'4' u'10' u'10' u'1' u'7' u'10' u'9' u'10' u'10' u'3' u'6' u'4'
 u'10' u'1' u'7' u'2' u'5' 0 u'10' u'8' u'8' u'8' u'10' u'6' u'10' u'8'
 u'10' u'10' u'9' u'9' u'1' 0 u'4' u'4' u'1']


In [419]:
arr = [str(r) for r in a]

In [420]:
arr

['0',
 '10',
 '1',
 '1',
 '1',
 '10',
 '10',
 '10',
 '10',
 '10',
 '7',
 '5',
 '2',
 '1',
 '6',
 '1',
 '1',
 '4',
 '4',
 '1',
 '1',
 '4',
 '3',
 '6',
 '4',
 '5',
 '6',
 '5',
 '1',
 '2',
 '1',
 '1',
 '1',
 '1',
 '3',
 '3',
 '7',
 '2',
 '1',
 '7',
 '5',
 '5',
 '1',
 '1',
 '7',
 '1',
 '1',
 '1',
 '1',
 '5',
 '5',
 '10',
 '1',
 '8',
 '1',
 '1',
 '8',
 '1',
 '1',
 '1',
 '7',
 '1',
 '10',
 '7',
 '8',
 '10',
 '1',
 '8',
 '10',
 '10',
 '10',
 '10',
 '10',
 '9',
 '10',
 '10',
 '1',
 '10',
 '10',
 '10',
 '10',
 '10',
 '9',
 '4',
 '10',
 '10',
 '1',
 '7',
 '10',
 '9',
 '10',
 '10',
 '3',
 '6',
 '4',
 '10',
 '1',
 '7',
 '2',
 '5',
 '0',
 '10',
 '8',
 '8',
 '8',
 '10',
 '6',
 '10',
 '8',
 '10',
 '10',
 '9',
 '9',
 '1',
 '0',
 '4',
 '4',
 '1']